# Generated by Django 4.1.3 on 2022-11-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_anotherdrink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnotherDrink',
        ),
    ]
