# Generated by Django 4.1.3 on 2022-11-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_categoria_compra_itemcompra_produto_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcompra',
            name='idCompra',
        ),
        migrations.RemoveField(
            model_name='itemcompra',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='ItemCompra',
        ),
    ]
