# Generated by Django 4.1.3 on 2022-11-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_itemcompra_idcompra_remove_itemcompra_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precoTotal', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricaoCompra', models.CharField(max_length=250)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('precoUnitario', models.FloatField()),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.produto')),
            ],
        ),
    ]
