# Generated by Django 4.1.3 on 2022-11-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_usuario_atribuicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='atribuicao',
            field=models.CharField(default='comprador', max_length=20),
        ),
    ]
