# Generated by Django 4.1.3 on 2022-11-02 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_usuario_atribuicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='idCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='ecommerce.compra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagemProduto',
            field=models.URLField(),
        ),
    ]
