# Generated by Django 4.1.3 on 2022-11-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_itemcompra_idcompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcompra',
            name='precoUnitario',
        ),
    ]
