# Generated by Django 4.1.3 on 2022-11-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_compra_itemcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='subTotal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
