# Generated by Django 4.1.3 on 2022-11-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_itemcompra_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='subTotal',
            field=models.FloatField(null=True),
        ),
    ]
