# Generated by Django 4.1.3 on 2022-11-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_alter_compra_precototal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='jwt',
        ),
    ]
